server:
  port: 8080

spring:
  application:
    name: craflyServer
  config:
    import: key-dev.yaml
    activate:
      on-profile: dev
  datasource:
    url: ${key.datasource.url}
    username: ${key.datasource.username}
    password: ${key.datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

springdoc:
  paths-to-match:
    - /v1/**

logging:
  #  file:
  #    name: logs/demo-all-in-one.log
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%-5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug
    org:
      springframework:
        web:
          servlet: debug