server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: craflyServer
  config:
    import: ${key.env.path}
  datasource:
    url: ${key.datasource.url}
    username: ${key.datasource.username}
    password: ${key.datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${key.oauth2.kakao.client-id}
            client-secret: ${key.oauth2.kakao.client-secret}
            client-authentication-method: client_secret_post
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
#              - profile_image
              - account_email

jwt:
  secret-key: ${key.jwt.secret-key}
  access-expired-time: ${key.jwt.access-expired-time}
  refresh-expired-time: ${key.jwt.refresh-expired-time}

login:
  path: /v1/user/login

springdoc:
  paths-to-match:
    - /v1/**